#!/bin/bash
# Ref: https://github.com/JonGabilondoAngulo/Organismo-Lib

app_name="$1"
if [ ! -d "/Applications/${app_name}.app" ]; then
    echo "[${app_name}] not found. Please download and install the app.\n"
    exit 1
fi
CurrentAppPath=$(cd $(dirname $0) && pwd)
dylib_path="${CurrentAppPath}/Versions/A/Organismo-mac"
DYLD_INSERT_LIBRARIES="$dylib_path" "/Applications/${app_name}.app/Contents/MacOS/${app_name}"
