#!/bin/bash
# Ref: https://github.com/JonGabilondoAngulo/Organismo-Lib

app_name="$1"
if [[ "$app_name" == /* ]]; then
    app_path="$app_name"
else
    app_path="/Applications/${app_name}.app/Contents/MacOS/${app_name}"
fi

if [ ! -f "$app_path" ]; then
    echo -e "\033[31mError: Application [$app_path] does not exist.\033[0m"
    exit 1
fi

CurrentAppPath=$(cd $(dirname $0) && pwd)
dylib_path="${CurrentAppPath}/Versions/A/Organismo-mac"
DYLD_INSERT_LIBRARIES="${dylib_path}" "${app_path}"
